"""Generate the complete 0.8.0 public API and CLI reference; --check detects drift."""

from __future__ import annotations

import argparse
import inspect
import sys
from dataclasses import fields, is_dataclass
from pathlib import Path
from typing import Any

import regista
from regista.cli import build_parser

ROOT = Path(__file__).resolve().parents[1]

ERRORS = {
    "PoolConfigurationError": "Invalid pool bounds or timeout.",
    "PoolExhaustedError": "No connection became available within the pool timeout.",
    "PoolUnavailableError": "The pool could not open or reach the database.",
    "DatabaseOperationError": "A PostgreSQL operation failed; the transaction was rolled back.",
    "UnsupportedSchemaError": "Unsupported destination for this operation.",
    "InvalidWorkflowError": "Invalid workflow definition, document or version assertion.",
    "InvalidQueryError": "Invalid query, page bound, filter, state name or cursor.",
    "TransitionRefusedError": "The pinned workflow refuses the transition or presented role.",
    "ClaimContestedError": "Another live lease already owns this item.",
    "StaleAttemptError": "The supplied attempt cannot authorize this operation.",
    "SequenceConflictError": "The item's locked sequence differs from expected_seq.",
    "InvalidFieldError": "Invalid JSON, field schema, reference, clear or required field.",
    "IdempotencyConflictError": "An idempotency key was reused for a different request.",
    "WorkItemNotFoundError": "The work item does not exist in this namespace.",
    "InputTooLargeError": "An input exceeds a declared size or depth limit.",
}


def describe(name: str, obj: Any) -> list[str]:
    out = [f"### `{name}`", ""]
    if isinstance(obj, type) and issubclass(obj, Exception):
        bases = ", ".join(base.__name__ for base in obj.__bases__)
        out += [f"Base: `{bases}`.", "", ERRORS.get(name, inspect.getdoc(obj) or ""), ""]
    elif isinstance(obj, type) or callable(obj):
        out += ["```python", f"{name}{inspect.signature(obj)}", "```", ""]
        # Use its own docstring: inherited object documentation is not a contract.
        if obj.__doc__:
            out += [inspect.cleandoc(obj.__doc__), ""]
        if is_dataclass(obj):
            out += ["Fields: " + ", ".join(f"`{f.name}: {f.type}`" for f in fields(obj)) + ".", ""]
        if isinstance(obj, type) and not issubclass(obj, Exception):
            for method_name in sorted(vars(obj)):
                if method_name.startswith("_"):
                    continue
                method = getattr(obj, method_name)
                if callable(method):
                    out += describe(f"{name}.{method_name}", method)
    else:
        value = ("frozenset(" + repr(tuple(sorted(obj))) + ")"
                 if isinstance(obj, frozenset) else repr(obj))
        out += ["```python", f"{name} = {value}", "```", ""]
    return out


def api_reference() -> str:
    out = [
        "# 0.8.0 public API reference", "",
        "Generated by `scripts/generate_reference.py` from `regista.__all__`, signatures,",
        "result fields and docstrings. Regenerate after changing the public surface.", "",
        "Use `Kernel.connect()` rather than constructing a pool manually; close the handle",
        "in a `finally` block. All database refusals derive from `KernelError`. Exception",
        "subclass relationships below let callers catch a broader refusal category.", "",
        "Roles and actors are trusted-host assertions. Replay is read-only consistency",
        "checking. See [trust and recovery](operations.md) and [the specification](../spec.md).",
        "The CLI exposes a narrower set of optional parameters; library signatures below",
        "define the complete public surface. Only names in `regista.__all__` are exports.", "",
    ]
    for name in regista.__all__:
        out += describe(name, getattr(regista, name))
    return "\n".join(out)


def cli_reference() -> str:
    out = [
        "# 0.8.0 CLI reference", "",
        "Generated from the actual parser by `scripts/generate_reference.py`.", "",
        "Global options precede commands: `regista --dsn DSN --schema PROJECT --json COMMAND`.",
        "`REGISTA_DSN` is the DSN fallback; schema defaults to `public`. Except workflow",
        "validation, commands open an existing baseline; `init` alone permits initialization.",
        "JSON mode emits JSON; whole-namespace `check-history` emits JSON Lines. Exit 0",
        "means success, 1 means history drift or workflow-validation failure, and 2 means",
        "a kernel refusal or command-line error. Refusals write `refused: ...` to stderr;",
        "`--json` also writes an error/message/exit_code object to stdout (otherwise empty).",
        "Human output escapes C0/C1, ESC, DEL, line breaks and bidi controls in all values;",
        "JSON serialization is unchanged. Malformed UUIDs/fields and JSON parser limits",
        "use the same exit-2 refusal envelope, without tracebacks.", "",
        "`--field key=value` repeats, parses a value as JSON when possible and otherwise",
        "keeps text. Transition `--unset-field` clears keys atomically. Roles are presented",
        "by a trusted caller; `--actor-kind` defaults to agent. There is no CLI payload flag.", "",
        "`list` and `history` return one page (50 by default, at most 500) and human output",
        "warns when full; JSON clients compare length to limit and resume explicitly.",
        "Workflow list is the library's default first page; for registry pagination use",
        "`Kernel.list_workflows(limit=..., after=(name, version))`. Show's outgoing links",
        "are also the default first page; use `Kernel.links_from` to paginate all links.", "",
        "The old `replay` command refuses. `check-history` is read-only and never repairs",
        "projections. Omit its ID for the whole namespace; quiesce it for restore checking.",
        "Leases persist until explicit release. Operators schedule `expire-leases`; service",
        "roles and manual project `DROP SCHEMA` remain operator responsibilities.", "",
        "Blocked discovery requires caller-supplied satisfied states, uses one hop and",
        "never gates claims. See [operations](operations.md) for trust/recovery boundaries.", "",
    ]

    def visit(parser: argparse.ArgumentParser, label: str) -> None:
        # Python 3.11 and 3.14 wrap the long root usage differently.
        # Normalize whitespace in usage only; retain every option and help text.
        usage, rest = parser.format_help().rstrip().split("\n\n", 1)
        help_text = " ".join(line.strip() for line in usage.splitlines()) + "\n\n" + rest
        out.extend([f"## `{label}`", "", "```text", help_text, "```", ""])
        for action in parser._actions:
            if isinstance(action, argparse._SubParsersAction):
                for name, child in action.choices.items():
                    visit(child, f"{label} {name}")

    visit(build_parser(), "regista")
    return "\n".join(out)


def main() -> int:
    checking = "--check" in sys.argv[1:]
    for name, content in (("api.md", api_reference()), ("cli.md", cli_reference())):
        path = ROOT / "docs" / name
        if checking:
            if not path.exists() or path.read_text() != content:
                print(f"reference drift: {path.relative_to(ROOT)}", file=sys.stderr)
                return 1
        else:
            path.write_text(content)
    print("API and CLI references are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
